-- MySQL Script generated by MySQL Workbench
-- Fri May  5 21:25:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RealEstateManagementDatabaseSystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RealEstateManagementDatabaseSystem` ;

-- -----------------------------------------------------
-- Schema RealEstateManagementDatabaseSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RealEstateManagementDatabaseSystem` DEFAULT CHARACTER SET utf8 ;
USE `RealEstateManagementDatabaseSystem` ;

-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`RegisteredUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`RegisteredUser` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`RegisteredUser` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`ProfessionalTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`ProfessionalTypes` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`ProfessionalTypes` (
  `type` CHAR(20) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Location` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Location` (
  `loc_id` INT NOT NULL,
  `state` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`loc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Firm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Firm` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Firm` (
  `firm_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `location` INT NULL,
  PRIMARY KEY (`firm_id`),
  INDEX `FK_Firm_Location_idx` (`location` ASC) VISIBLE,
  CONSTRAINT `FK_Firm_Location`
    FOREIGN KEY (`location`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Location` (`loc_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Account` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Account` (
  `account_id` INT NOT NULL,
  `user` VARCHAR(45) NULL,
  `profession` CHAR(20) NULL,
  `firstname` CHAR(20) NULL,
  `lastname` CHAR(20) NULL,
  `zipcode` INT NULL,
  `phonenumber` CHAR(20) NULL,
  `firm` INT NULL,
  INDEX `FK_Account_User_idx` (`user` ASC) VISIBLE,
  INDEX `FK_Account_Profession_idx` (`profession` ASC) VISIBLE,
  INDEX `FK_Account_Firm_idx` (`firm` ASC) VISIBLE,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `FK_Account_User`
    FOREIGN KEY (`user`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`RegisteredUser` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Account_Profession`
    FOREIGN KEY (`profession`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`ProfessionalTypes` (`type`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Account_Firm`
    FOREIGN KEY (`firm`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Firm` (`firm_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Property` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Property` (
  `property_id` INT NOT NULL,
  `user` VARCHAR(45) NULL,
  `location` INT NULL,
  `listed` TINYINT NULL,
  PRIMARY KEY (`property_id`),
  INDEX `FK_Property_User_idx` (`user` ASC) VISIBLE,
  INDEX `FK_Property_Location_idx` (`location` ASC) VISIBLE,
  CONSTRAINT `FK_Property_User`
    FOREIGN KEY (`user`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`RegisteredUser` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Property_Location`
    FOREIGN KEY (`location`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Location` (`loc_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`MultiMediaContent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`MultiMediaContent` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`MultiMediaContent` (
  `content_id` TINYINT NOT NULL,
  `title` VARCHAR(45) NULL,
  `created` VARCHAR(45) NULL,
  `property` INT NULL,
  PRIMARY KEY (`content_id`),
  INDEX `FK_MultiMediaContent_User_idx` (`created` ASC) VISIBLE,
  INDEX `FK_MultiMediaContent_Property_idx` (`property` ASC) VISIBLE,
  CONSTRAINT `FK_MultiMediaContent_User`
    FOREIGN KEY (`created`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`RegisteredUser` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MultiMediaContent_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Profile` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Profile` (
  `profile_id` INT NOT NULL,
  `screenname` VARCHAR(45) NULL,
  `user` VARCHAR(45) NULL,
  `photo` TINYINT NULL,
  INDEX `FK_Profile_User_idx` (`user` ASC) VISIBLE,
  INDEX `FK_Profile_Photo_idx` (`photo` ASC) VISIBLE,
  PRIMARY KEY (`profile_id`),
  CONSTRAINT `FK_Profile_User`
    FOREIGN KEY (`user`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`RegisteredUser` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Profile_Photo`
    FOREIGN KEY (`photo`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`MultiMediaContent` (`content_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Room` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Room` (
  `room_id` INT NOT NULL,
  `property` INT NULL,
  `name` VARCHAR(45) NULL,
  `level` VARCHAR(45) NULL,
  `area` INT NULL,
  `dim_len` INT NULL,
  `dim_wid` INT NULL,
  `features` VARCHAR(45) NULL,
  PRIMARY KEY (`room_id`),
  INDEX `FK_Room_Property_idx` (`property` ASC) VISIBLE,
  CONSTRAINT `FK_Room_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`InteriorFactsandFeatures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`InteriorFactsandFeatures` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`InteriorFactsandFeatures` (
  `interiorff_id` INT NOT NULL,
  `property` INT NULL,
  `bedrooms` INT NULL,
  `bathroom` INT NULL,
  `fullbathrooms` INT NULL,
  `halfbathrooms` INT NULL,
  `flooring` VARCHAR(45) NULL,
  `heating` VARCHAR(45) NULL,
  `cooling` VARCHAR(45) NULL,
  `appliances` VARCHAR(45) NULL,
  `parking` VARCHAR(45) NULL,
  `laundry` VARCHAR(45) NULL,
  `pets` VARCHAR(45) NULL,
  `totalstructurearea` INT NULL,
  `totallivablearea` INT NULL,
  PRIMARY KEY (`interiorff_id`),
  INDEX `FK_InteriorFactsandFeatures_Property_idx` (`property` ASC) VISIBLE,
  CONSTRAINT `FK_InteriorFactsandFeatures_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`PropertyFactsandFeatures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`PropertyFactsandFeatures` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`PropertyFactsandFeatures` (
  `propff_id` INT NOT NULL,
  `property` INT NULL,
  `accessibility` VARCHAR(45) NULL,
  `levels` VARCHAR(45) NULL,
  `stories` INT NULL,
  `viewdescription` VARCHAR(45) NULL,
  `lotfeatures` VARCHAR(45) NULL,
  `attatchedtoanother` TINYINT NULL,
  `specialcond` VARCHAR(45) NULL,
  PRIMARY KEY (`propff_id`),
  INDEX `FK_PropertyFactsandFeatures_Property_idx` (`property` ASC) VISIBLE,
  CONSTRAINT `FK_PropertyFactsandFeatures_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`ConstructionDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`ConstructionDetails` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`ConstructionDetails` (
  `constdet_id` INT NOT NULL,
  `property` INT NULL,
  `type` VARCHAR(45) NULL,
  `archstyle` VARCHAR(45) NULL,
  `subtype` VARCHAR(45) NULL,
  `materials` VARCHAR(45) NULL,
  `roof` VARCHAR(45) NULL,
  `condition` VARCHAR(45) NULL,
  `new` TINYINT NULL,
  `yearbuilt` INT NULL,
  PRIMARY KEY (`constdet_id`),
  INDEX `FK_ConstructionDetails_Property_idx` (`property` ASC) VISIBLE,
  CONSTRAINT `FK_ConstructionDetails_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`UtilitiesandEnergyDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`UtilitiesandEnergyDetails` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`UtilitiesandEnergyDetails` (
  `utilenergy_id` INT NOT NULL,
  `property` INT NULL,
  `info` VARCHAR(45) NULL,
  `sewage` VARCHAR(45) NULL,
  `utilities` VARCHAR(45) NULL,
  `energyefficient` VARCHAR(45) NULL,
  `security` VARCHAR(45) NULL,
  PRIMARY KEY (`utilenergy_id`),
  INDEX `FK_UtilitiesandEnergyDetails_Property_idx` (`property` ASC) VISIBLE,
  CONSTRAINT `FK_UtilitiesandEnergyDetails_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`HOAFinancials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`HOAFinancials` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`HOAFinancials` (
  `financials_id` INT NOT NULL,
  `property` INT NULL,
  `yrprice` INT NULL,
  `monthprice` INT NULL,
  `pricerangehigh` INT NULL,
  `pricerangelow` INT NULL,
  `hoafee` INT NULL,
  `amenities` VARCHAR(45) NULL,
  `services` VARCHAR(45) NULL,
  `associationname` VARCHAR(45) NULL,
  `buyeragencycomp` DECIMAL NULL,
  PRIMARY KEY (`financials_id`),
  INDEX `FK_HOAFinancials_Property_idx` (`property` ASC) VISIBLE,
  CONSTRAINT `FK_HOAFinancials_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`ExternalECommerceSites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`ExternalECommerceSites` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`ExternalECommerceSites` (
  `name` VARCHAR(45) NOT NULL,
  `websitelink` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Advertisement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Advertisement` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Advertisement` (
  `ad_id` INT NOT NULL,
  `property` INT NULL,
  `ecommercesite` VARCHAR(45) NULL,
  `message` TEXT(1000) NOT NULL,
  `photo` TINYINT NULL,
  PRIMARY KEY (`ad_id`),
  INDEX `FK_Advertisement_Property_idx` (`property` ASC) VISIBLE,
  INDEX `FK_Advertisement_ECommerceSite_idx` (`ecommercesite` ASC) VISIBLE,
  INDEX `FK_Advertisement_Photo_idx` (`photo` ASC) VISIBLE,
  CONSTRAINT `FK_Advertisement_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Advertisement_ECommerceSite`
    FOREIGN KEY (`ecommercesite`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`ExternalECommerceSites` (`name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Advertisement_Photo`
    FOREIGN KEY (`photo`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`MultiMediaContent` (`content_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Application` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Application` (
  `app_id` INT NOT NULL,
  `property` INT NULL,
  `user` VARCHAR(45) NULL,
  `message` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`app_id`),
  INDEX `FK_Application_Property_idx` (`property` ASC) VISIBLE,
  INDEX `FK_Application_User_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `FK_Application_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Application_User`
    FOREIGN KEY (`user`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`RegisteredUser` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Region` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Region` (
  `region_id` TINYINT NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`ContentDeliveryNetwork`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`ContentDeliveryNetwork` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`ContentDeliveryNetwork` (
  `cdn_id` TINYINT NOT NULL,
  `region` TINYINT NULL,
  `description` VARCHAR(255) NULL,
  `numcopies` INT NULL,
  PRIMARY KEY (`cdn_id`),
  INDEX `FK_CDN_Region_idx` (`region` ASC) VISIBLE,
  CONSTRAINT `FK_CDN_Region`
    FOREIGN KEY (`region`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Region` (`region_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`MediaHosted`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`MediaHosted` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`MediaHosted` (
  `media_hosted` TINYINT NOT NULL,
  `media` TINYINT NULL,
  `cdn` TINYINT NULL,
  PRIMARY KEY (`media_hosted`),
  INDEX `FK_MediaHosted_CDN_idx` (`cdn` ASC) VISIBLE,
  INDEX `FK_MediaHosted_MultiMediaContent_idx` (`media` ASC) VISIBLE,
  CONSTRAINT `FK_MediaHosted_CDN`
    FOREIGN KEY (`cdn`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`ContentDeliveryNetwork` (`cdn_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MediaHosted_MultiMediaContent`
    FOREIGN KEY (`media`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`MultiMediaContent` (`content_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Video` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Video` (
  `video_id` TINYINT NOT NULL,
  `content_type` TINYINT NULL,
  `length` INT NULL,
  PRIMARY KEY (`video_id`),
  INDEX `FK_Video_Multimedia_idx` (`content_type` ASC) VISIBLE,
  CONSTRAINT `FK_Video_MultiMediaContent`
    FOREIGN KEY (`content_type`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`MultiMediaContent` (`content_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`Photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`Photo` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`Photo` (
  `photo_id` TINYINT NOT NULL,
  `content_type` TINYINT NULL,
  `publisher` VARCHAR(45) NULL,
  PRIMARY KEY (`photo_id`),
  INDEX `FK_Photo_Multimedia_idx` (`content_type` ASC) VISIBLE,
  CONSTRAINT `FK_Photo_MultiMediaContent`
    FOREIGN KEY (`content_type`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`MultiMediaContent` (`content_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RealEstateManagementDatabaseSystem`.`SavedProperty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RealEstateManagementDatabaseSystem`.`SavedProperty` ;

CREATE TABLE IF NOT EXISTS `RealEstateManagementDatabaseSystem`.`SavedProperty` (
  `property` INT NULL,
  `user` VARCHAR(45) NULL,
  INDEX `FK_SavedProperty_Property_idx` (`property` ASC) VISIBLE,
  INDEX `FK_SavedProperty_User_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `FK_SavedProperty_Property`
    FOREIGN KEY (`property`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`Property` (`property_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SavedProperty_User`
    FOREIGN KEY (`user`)
    REFERENCES `RealEstateManagementDatabaseSystem`.`RegisteredUser` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
